/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Context": {                                     "en": "Context",                                         "de": "Kontext",                                         "ru": "Контекст",                                        "pt": "Contexto",                                        "nl": "verband",                                         "fr": "Contexte",                                        "it": "contesto",                                        "es": "Contexto",                                        "pl": "Kontekst",                                        "zh-cn": "内容"},
    "Error timeout(ms):": {                          "en": "Error timeout (ms)",                              "de": "Fehler-Timeout (ms)",                             "ru": "Тайм-аут ошибки (мс)",                            "pt": "Tempo limite de erro (ms)",                       "nl": "Fout-time-out (ms)",                              "fr": "Délai d'erreur (ms)",                             "it": "Timeout errore (ms)",                             "es": "Tiempo de espera de error (ms)",                  "pl": "Błąd limitu czasu (ms)",                          "zh-cn": "错误超时（毫秒）"},
    "Extend WEB adapter:": {                         "en": "Use as web adapter extension",                    "de": "Als Web-Adapter-Erweiterung nutzen",              "ru": "Использовать, как расширение web-драйвера",       "pt": "Use como uma extensão do adaptador da web",       "nl": "Breid WEB-adapter uit",                           "fr": "Étendre l'adaptateur WEB",                        "it": "Estendi la scheda WEB",                           "es": "Extender el adaptador WEB",                       "pl": "Przedłuż adapter WEB",                            "zh-cn": "扩展WEB适配器"},
    "Paths": {                                       "en": "Paths",                                           "de": "Pfade",                                           "ru": "пути",                                            "pt": "Caminhos",                                        "nl": "Paths",                                           "fr": "Chemins",                                         "it": "percorsi",                                        "es": "Caminos",                                         "pl": "Ścieżki",                                         "zh-cn": "路径"},
    "Proxy adapter settings": {                      "en": "Proxy adapter settings",                          "de": "Proxy Adapter Einstellungen",                     "ru": "Настройки Proxy драйвера",                        "pt": "Configurações do adaptador proxy",                "nl": "Proxy-adapterinstellingen",                       "fr": "Paramètres de l'adaptateur proxy",                "it": "Impostazioni dell'adattatore proxy",              "es": "Configuración del adaptador proxy",               "pl": "Ustawienia adaptera proxy",                       "zh-cn": "代理适配器设置"},
    "Route path:": {                                 "en": "Route path",                                      "de": "Routenpfad",                                      "ru": "Путь в URL",                                      "pt": "Caminho da rota",                                 "nl": "Route pad",                                       "fr": "Chemin d'itinéraire",                             "it": "Percorso percorso",                               "es": "Ruta de la ruta",                                 "pl": "Ścieżka trasy",                                   "zh-cn": "路线路径"},
    "Timeout": {                                     "en": "Timeout",                                         "de": "Timeout",                                         "ru": "Тайм-аут",                                        "pt": "Tempo limite",                                    "nl": "timeout",                                         "fr": "Timeout",                                         "it": "timeout",                                         "es": "Tiempo de espera",                                "pl": "Limit czasu",                                     "zh-cn": "超时"},
    "URL": {                                         "en": "URL",                                             "de": "URL",                                             "ru": "URL",                                             "pt": "URL",                                             "nl": "URL",                                             "fr": "URL",                                             "it": "URL",                                             "es": "URL",                                             "pl": "URL",                                             "zh-cn": "网址"},
    "Use simple proxy (no sockets)": {               "en": "Use simple proxy (no sockets)",                   "de": "Einfachen Proxy verwenden (keine Sockets)",       "ru": "Простой прокси (без сокетов)",                    "pt": "Use proxy simples (sem soquetes)",                "nl": "Gebruik eenvoudige proxy (geen sockets)",         "fr": "Utiliser un proxy simple (pas de sockets)",       "it": "Usa proxy semplice (senza prese)",                "es": "Usar proxy simple (sin sockets)",                 "pl": "Użyj prostego proxy (bez gniazd)",                "zh-cn": "使用简单代理（无套接字）"},
    "all": {                                         "en": "all",                                             "de": "alle",                                            "ru": "все",                                             "pt": "todos",                                           "nl": "alle",                                            "fr": "tout",                                            "it": "tutto",                                           "es": "todo",                                            "pl": "wszystko",                                        "zh-cn": "全部"},
};